sudo: false

language: python

addons:
  apt:
    packages:
    - ruby-dev
    - gcc

cache:
  apt: true

matrix:
  include:
    - python: "3.5"
      env: QT_API=pyqt5
      os: linux
    - python: "3.5"
      env: QT_API=pyqt4
      os: linux
    - python: "2.7"
      env: QT_API=pyside
      os: linux

before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3

install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -f -p $HOME/miniconda;
- export PATH="$HOME/miniconda/bin:$PATH";
- hash -r;
- conda config --set always_yes yes --set changeps1 no;
- conda update -q conda;
- conda install -n root _license;

- conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION;
- source activate testenv

- export REQUIREMENTS=`cat requirements.txt | tr '\n' ' ' | sed 's/pyhmsa//g' | sed 's/qtpy//g'`
- if [[ "$QT_API" == "pyqt5" ]]; then
    conda config --add channels spyder-ide;
    export REQUIREMENTS=$REQUIREMENTS" qt5 pyqt5";
  elif [[ "$QT_API" == "pyqt4" ]]; then
    export REQUIREMENTS=$REQUIREMENTS" qt pyqt";
  elif [[ "$QT_API" == "pyside" ]]; then
    export REQUIREMENTS=$REQUIREMENTS" qt pyside";
  fi
- conda install $REQUIREMENTS
- pip install qtpy pyhmsa codecov
- python setup.py develop

script:
- nosetests

after_success:
- codecov

notifications:
  email: false

before_deploy:
- gem install fpm
- python setup.py bdist_deb

deploy:
  - provider: pypi
    user: philippe.pinard
    password:
      secure: hJP3Ghy7+SMGczbrMSt9oMFimM4BbvkK+g4dnRshYu96LZ6vdfeX34rBtySH7mGEj4yoJ2+Bh0oDzsOy/rPQvTwCF4R00Zad8lExFarNuZuYS5v3+YALGzwvGUjsLIuboP1AkGDZ+okEgxNkB2sGmJudqklimVpO0lc1heGnkmnjwcrMJyliejARM68bep+1gtIbpCQZDpeLUjvTzve3yasY8kqY0Pe0RjqXcLfthL9GEyHSQldLKC8L0cQo4eGgb4aN6LffesNsazUCiODjVNlaBLuDWRMsLprYkxt9XQjrHVLK812zSGmBxm3/EKK53TpYzLXgw47tFOBjcgBZSv76//X3N9jzpj2aaKMdNnh9cygNNRFJioxC2wt9y3Z6TvMiydwD+Y7CAAv9fe03CYYlv07OVgrjBGivAdzYiqid9GQaUrSgFR5uX2+1hMeKjtxrwRvVDpH1sDRvUhSxbjxCJuNgCgZfvKrGxVd1xBFhQHu2t0ZDJQR1/FS/Q3I2mi8i4bECtp3VKnFgiUIBNn0KY8QXqwGxzPXpiKDzKLMDN5xZxPAjEc6UjC5k6pndxWXYQ6mMAXxnCgY2WJmkWwlLtN6vgz2FEAtTj2fAV132MXvu3Z+WAamsgSXHTKSKv3vtEyYR0pjaOf/ti7l+3PZbKNdV033Nb+QS+TWF01s=
    distributions: sdist
    on:
      tags: true
      repo: pyhmsa/pyhmsa-gui
      all_branches: true
  - provider: packagecloud
    repository: hmsa
    username: ppinard
    dist: ubuntu/precise
    skip_cleanup: true
    local-dir: dist
    token:
      secure: CSbCqBfAa9OvhfCr7T8pnOqVvgNHQZ/ipM+WEpUx2WR41Cg2wIQXUtdkOgS/G1gcugnRk6La9HK0y9bWj1DDOaeRHLxgVnkIfLfi4uMKn0yloOY+nn+81DVz/m0Fqo0ciWRTqaXiLixqIV9OdVjqEg1SS0/vnB715d6SMIpQ/NW+jI9Do/78ZrcsJJMBXGlnlTI9yLIdEnaeiab3OSBJvd32q+s+eMdluPfjhgNWs48pysZ4qx3rhSR2EtmNRTZ2rI09ykdEobZR+xzodCG2e8xGkX4aqrEkVXPF8Abx7UMwlyWH18sURboRs9imCe120g2GuCsfQI6jiUJdN6FfYzEWvaBxmEuBmcNpJ2gGDx0jdsScxwfiOFvgeHvEPQvXpt7CwnQY2HBDIG0qc02J7r4OMgvH5IlnOZfBWqKcjFpeblZalJ386KznHlQwDYnDRqixf5KVcScpkji50z35r3Ga1VL6qSuTouQXCd6KMgyAsU4tA8XKQHJwbzW5fMFn0qk238tb39kV5vzsS8AGTxYRKLiHGlqXsT2W0+4MBEtwtJ+xAjaM/6RrytGD5dAdSxhAQuyXwy/bxk9k5cUj+z2tbDVwx2Hp2S/zmQ6cNFl6nn4o5YYu+2R1bAsyRm19nM5bPDyxaxTcWqXl1KarUD//6RVhQ5zMXa1SOku5g6Q=
    on:
      tags: true
      repo: pyhmsa/pyhmsa-gui
      all_branches: true