sudo: false
language: python
addons:
  apt:
    packages:
    - ruby-dev
    - gcc
cache:
  directories:
    - $HOME/.pip-cache/
python:
- '2.7'
- '3.4'
before_install:
- pip install --upgrade pip
- pip install --cache-dir $HOME/.pip-cache codecov
- gem install fpm
install:
- pip install -v -v -v --cache-dir $HOME/.pip-cache -r requirements.txt
- python setup.py develop
script:
- nosetests
notifications:
  email: false
deploy:
  - provider: pypi
    user: philippe.pinard
    password:
      secure: nC/0Lj2H/5BZo4BAhc29fYa6AJZL+UBVfFBcoX57XMA3AD+iCHWH0HJJXoiGvKtP3M/NB1tXAB+5Tj0R6q0bUOiMnf$
    distributions: "sdist bdist_wheel"
    on:
      tags: true
      repo: pyhmsa/pyhmsa-gui
      all_branches: true
  - provider: packagecloud
    repository: hmsa
    username: ppinard
    dist: ubuntu/precise
    skip_cleanup: true
    local-dir: dist
    token:
      secure: n93Y348IqhGkoztlAJ8HIfs48kGIpyvp4ZZICM34dqseWKX2BkZwU3/fWEob9OT038rIcWNgOr3+VUqQyI0JTIvAU0rvvVbEvDN6yCbRFo8ckMvMLThe0pXHecpDxWjg3BuQJXDOdc7IuqhZU948yEH9OeOinRFhIDMK97Tz56Q=
    on:
      tags: true
      repo: pyhmsa/pyhmsa-gui
      all_branches: true
